version: '3.8'

services:
  frontend-client:
    build:
      context: ./front
      dockerfile: Dockerfile.client
    ports:
      - "3899:80"
    env_file: ./front/.env
    networks:
      - app-network
    depends_on:
      - backend
  frontend-admin:
    build:
      context: ./front-admin
      dockerfile: Dockerfile
    ports:
      - "3900:80"
    env_file: ./front-admin/.env
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    image: accord:latest
    build:
      context: ./
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/uploads:/uploads
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./Backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend-client
      - frontend-admin
    networks:
      - app-network
networks:
  app-network: