version: '3.8'

services:
  frontend-client:
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file: ./front/.env
    ports:
      - "3899:3899"
    networks:
      - app-network
    depends_on:
      - backend
  frontend-admin:
    build:
      context: ./front-admin
      dockerfile: Dockerfile
    ports:
      - "3900:3900"
    env_file: ./front-admin/.env
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    image: accord:latest
    build:
      context: ./Backend/
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/uploads:/uploads
    networks:
      - app-network
networks:
  app-network: