version: '3.8'

services:
  frontend-client:
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file: ./front/.env
    ports:
      - "3899:3899"
    networks:
      - app-network
    depends_on:
      - backend
  frontend-admin:
    build:
      context: ./front-admin
      dockerfile: Dockerfile
    ports:
      - "3900:3900"
    env_file: ./front-admin/.env
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend/
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/uploads:/uploads
    environment:
      #app
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.ru:3306/"
      SPRING_DATASOURCE_USERNAME: "example_login"
      SPRING_DATASOURCE_PASSWORD: "oiefowenjf"
      SPRING_DATA_JPA_REPOSITORIES_ENABLED: "true"

      # Geonames
      GEONAMES_LOGIN: "Login"
      GEONAMES_API_URL: "http://api.geonames.org/searchJSON"

      # Admin data
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "securePassword12345"
    networks:
      - app-network
networks:
  app-network: